revert HttpUrl to str due to "Error binding parameter 5 - probably unsupported type."
InterfaceError: (sqlite3.InterfaceError) Error binding parameter 5 - probably unsupported type.
[SQL: INSERT INTO compliance_framework (compliance_framework_id, name, abbreviation, description, logo, homepage, status, observed_at) VALUES (?, ?, ?, ?, ?, ?,
?, ?), (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (compliance_framework_id) DO UPDATE SET name = excluded.name, abbreviation = excluded.abbreviation, description =
excluded.description, logo = excluded.logo, homepage = excluded.homepage, status = excluded.status, observed_at = excluded.observed_at]
[parameters: ('hipaa', 'The Health Insurance Portability and Accountability Act', 'HIPAA', "HIPAA (Health Insurance Portability and Accountability Act) is a
U.S. federal law designed to safeguard the privacy and security of individuals' health information, establishing standards for its protection and regulating its
use in the healthcare industry.", None, Url('https://www.cdc.gov/phlp/publications/topic/hipaa.html'), 'ACTIVE', '2024-03-22 22:26:49.152081', 'soc2t2', 'System
and Organization Controls Level 2 Type 2', 'SOC 2 Type 2', "SOC 2 Type 2 is a framework for assessing and certifying the effectiveness of a service
organization's information security policies and procedures over time, emphasizing the operational aspects and ongoing monitoring of controls.", None,
Url('https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2'), 'ACTIVE', '2024-03-22 22:26:49.152170')]
(Background on this error at: https://sqlalche.me/e/20/rvf5)